server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/