server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: product_high
          uri: lb://product
          predicates:
            - Path=/products/**
            - Weight=product-group, 70
        - id: product_low
          uri: lb://product
          predicates:
            - Path=/products/**
            - Weight=product-group, 30
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


service:
  jwt:
    access-expiration: 600000 # 10분
    refresh-expiration: 10800000 # 3시간
    secret-key: "a0eaadde03310f7e8ab93ac3290ca86565ac459fa73fb1fb3cbf8022e4ddd422705bba58b6983fc7ffdde7c833ea4eb69d9f70ed60a99f1bad482c23a0e92fd8"