spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msa
    username: postgres
    password: spartaMsa
    driver-class-name: org.postgresql.Driver

service:
  jwt:
    access-expiration: 600000 # 10분
    refresh-expiration: 10800000 # 3시간
    secret-key: "a0eaadde03310f7e8ab93ac3290ca86565ac459fa73fb1fb3cbf8022e4ddd422705bba58b6983fc7ffdde7c833ea4eb69d9f70ed60a99f1bad482c23a0e92fd8"