spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: product_high
          uri: lb://product
          predicates:
            - Path=/products/**
            - Weight=product-group, 60
        - id: product_low
          uri: lb://product
          predicates:
            - Path=/products/**
            - Weight=product-group, 40
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true