server:
  port: 19096
spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repository
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/