### 회원가입
POST localhost:19091/auth/sign-up
Content-Type: application/json

{
  "username": "jwtUtilTest",
  "password": "1234"
}

### 로그인
POST localhost:19091/auth/sign-in
Content-Type: application/json

{
  "username": "jwtUtilTest",
  "password": "1234"
}

### 토큰 갱신
PUT localhost:19091/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJhdXRoIiwiaWF0IjoxNzMzMjA0NDIzLCJleHAiOjE3MzMyMDUwMjN9.AgyudQ4g6U9Hfdc-TZBQvgLenzRTBVi6zgUReZcMqqMT1VocJx97nq3gM4xyBCxRWkXIwFZji8hNwaOmRN9NTw
X-Refresh-Token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJhdXRoIiwiaWF0IjoxNzMzMjA0NDIzLCJleHAiOjE3MzMyMTUyMjN9.ERRS5HI8NjFrh6TpzzqVHLgn8qQdkfLrmLR6II2eLDeIJdbMZ3g1CHoWqcM2hkmrWxNzuSDILjkFZHk9DMkdYw
